"""empty message

Revision ID: f76a14d27045
Revises: b73dea971b6d
Create Date: 2025-01-15 09:35:35.425092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76a14d27045'
down_revision = 'b73dea971b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('pictures',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=800),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=800),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('pictures',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
